# MCP Server
db_file_path: ./database/subreddit.db

embeddings:
  file_path: ./embeddings/subreddit_embeddings.jsonl
  persist_in_gpu: true

subreddit:
  - name: subreddit1
    description: Description of subreddit1
  - name: subreddit2
    description: Description of subreddit2

server:
  host: localhost
  port: 8000

# MCP Client
system_prompt: You are a helpful assistant.

base_url: http://localhost:8080/v1/
api_key: your_api_key_here
model: llama-3.1-8B
server_url: http://localhost:8000/sse
llama_swap_no_persist: false